---
name: CPAN-Reporter-Smoker
version: 0.01_01
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: Turnkey CPAN Testers smoking
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
  repository: http://dagolden.googlecode.com/svn/
requires:
  CPAN: 1.92
  CPAN::Reporter: 1.07_02
  File::Spec: 3.27
  File::Temp: 0.2
  IO::File: 0
  Module::Build: 0.2808
  Probe::Perl: 0
  perl: 5.006
build_requires:
  Test::More: 0.74
provides:
  CPAN::Reporter::Smoker:
    file: lib/CPAN/Reporter/Smoker.pm
    version: 0.01_01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
