---
name: CPAN-Reporter-Smoker
version: 0.19
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: Turnkey CPAN Testers smoking
license: apache
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
  repository: http://dagolden.googlecode.com/svn/
requires:
  CPAN: 1.93
  CPAN::HandleConfig: 0
  CPAN::Reporter::History: 1.1702
  CPAN::Tarzip: 0
  Carp: 0
  Compress::Zlib: 1.2
  Exporter: 0
  ExtUtils::MakeMaker: 6.46
  Fcntl: 0
  File::Basename: 0
  File::Spec: 3.27
  File::Temp: 0.2
  Module::Build: 0.3
  Probe::Perl: 0.01
  Term::Title: 0.01
  Test::Reporter: 1.52
  perl: 5.006
build_requires:
  Cwd: 3.27
  File::Path: 0
  IO::CaptureOutput: 1.06
  IO::File: 0
  Test::More: 0.62
provides:
  CPAN::Reporter::Smoker:
    file: lib/CPAN/Reporter/Smoker.pm
    version: 0.19
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
no_index:
  directory:
    - examples
    - inc
