use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Bam
Baz
CTRL
Distroprefs
SIGKILL
cpanreporter
defaultdeps
distroprefs
kurila
minicpanrc
prerelease
titlebar
untarring
urllist
David
Golden
dagolden
Alexandr
Ciornii
alexchorny
Christian
Walde
walde
lib
CPAN
Reporter
Smoker
